Add NixOS module
memflow/memflow-nixos pull request #3
Opened 2022-01-09 18:47 UTC by babbaj

2022-01-09 22:36 UTC, weewoo22 requested changes

2022-01-09 22:36 UTC, weewoo22 commented on flake.nix
> +            boot.kernelPatches = [{
I don't think `boot.kernelPatches` is the correct way to provide kernel configuration from a module. None of the modules in Nixpkgs that provide kernel modules use it to provide needed config options. Should use something like https://github.com/NixOS/nixpkgs/blob/a3543230e420f027bb148ad8fe82af2df68f52c6/nixos/modules/hardware/video/amdgpu-pro.nix#L35-L37 & https://github.com/NixOS/nixpkgs/blob/a3543230e420f027bb148ad8fe82af2df68f52c6/nixos/modules/hardware/video/amdgpu-pro.nix#L49-L52

2022-01-09 22:36 UTC, weewoo22 commented on flake.nix
> +                KALLSYMS y
`KALLSYMS` is already enabled in the default kernel configuration. Nixpkg modules that require `KALLSYMS_ALL` have it enabled alone (see: https://github.com/NixOS/nixpkgs/blob/a3543230e420f027bb148ad8fe82af2df68f52c6/nixos/modules/hardware/video/amdgpu-pro.nix#L39)
```suggestion
```

2022-01-09 22:36 UTC, weewoo22 commented on flake.nix
> +            name = "memflow-enable-kallsyms";
More specifically
```suggestion
            name = "memflow-enable-kallsyms-all";
```

2022-01-09 22:36 UTC, weewoo22 commented on flake.nix
> +            boot.kernelModules = [ "memflow" ];
We should leave it up to the user if they want to have the module load on boot or not.
```suggestion
```

2022-01-09 22:36 UTC, weewoo22 commented on flake.nix
> +            boot.extraModulePackages = [ (self.memflow-kmod.${builtins.currentSystem} config.boot.kernelPackages.kernel) ];
`builtins.currentSystem` is impure
```suggestion
            boot.extraModulePackages = [ (self.memflow-kmod.${pkgs.system} config.boot.kernelPackages.kernel) ];
```

2022-01-09 23:05 UTC, babbaj commented on flake.nix
> +            boot.kernelPatches = [{
nixos wiki disagrees 
![image](https://user-images.githubusercontent.com/12820770/148704871-b9126ad5-da32-477e-8ae9-5e4b4f7cfd25.png)

2022-01-10 11:05 UTC, weewoo22 commented
Okay, I changed my mind and changed it back to a one-size-fits-all config option that both patches the kernel config and auto loads the kmod: `memflow.kvm.enable`. Still not too sure about the kernel config patching since it's really meant for unconditionally applying extra kernel config options not ensuring config options, i.e. it will trigger a kernel build even if you already had the option set from something else. LGTM though. Squash it and I'll merge it once my kernel build finishes and I try it to make sure all is well.

2022-01-10 13:54 UTC, babbaj commented
There's no point in removing the options for enabling the kernel patch and auto loading the module. They were defaulted to true so just having enable = true was enough for it to all work

2022-01-10 19:59 UTC, weewoo22 commented
Okay, we'll keep the `loadModule` option defaulted to `true`. I just removed it because I thought we don't need that much config granularity really.

2022-01-11 02:19 UTC, merged